### ISSUE TITLE
Can't delete/disconnect wrong issues from advisory

### ISSUE THREAD

**Issue by IchHabRecht** [helhum/TYPO3.IHS#111]
If I try to add an issue for an unknown extension (product) I'm not able to save the advisory. Unfortunately I can't neither disconnect that issue nor delete it to save the advisory.
![2015-06-16_170503](https://cloud.githubusercontent.com/assets/1453345/8186354/17aadbcc-144a-11e5-9562-355d68b600ba.jpg)

**Comment by mberhorst** [comment]
The problem relies on a wrong assumption I had where the object identifier only exists when the object is persistent. I will fix this.
