### ISSUE TITLE
Deleting a link in an advisory leads to a 500

### ISSUE THREAD

**Issue by maddy2101** [helhum/TYPO3.IHS#119]
Situation: Building up advisory and add link to issue (not solution!). Then delete the link. Message says link is deleted. Update the advisory leads to 

```
500 Internal Server Error

An internal error occurred.

When contacting the maintainer of this application please mention the following reference code:

201511221057194e418f
```

**Comment by timkandel** [comment]
This is most likely the same error as in #108. Will have a look.
