### ISSUE TITLE
decouple JavaScript from actual HTML structure

### ISSUE THREAD

**Issue by helhum** [helhum/TYPO3.IHS#58]
#57 #56 seem to be related and reason seems to be changed HTML

wherever possible the JavaScript should not be closely coupled to HTML implementation (e.g. `closest('li')`) but rely on stable data attributes.

While changing this, custom (invalid) properties like `vulnerabilityTypeUrl="/url/to/foo"` should be change to data attributes `data-vulnerabilityTypeUrl="/url/to/foo"`

**Comment by timkandel** [comment]
Refactored in 7198f5fb3dc70f0ea0fb0012ca124054532dc6b5 and d62d5fff0dfaf16390568027ffcf6171e1f0ab9a
