### ISSUE TITLE
Solutions: Should "fixed in version" only contain versions from the parent issue

### ISSUE THREAD

**Issue by mberhorst** [helhum/TYPO3.IHS#61]
Should "fixed in version" only contain versions from the parent issue?

**Comment by helhum** [comment]
Yes, "fixed in version" in a Solution should only contain versions from the product in the parent Issue

**Comment by mberhorst** [comment]
https://github.com/helhum/TYPO3.IHS/commit/59258b51a7a4e36265e30d18f1e7da3ce11f086a
