### ISSUE TITLE
Not possible to remove an attached Issue

### ISSUE THREAD

**Issue by helhum** [helhum/TYPO3.IHS#64]
Steps to reproduce:

* Add issue to advisory without title (so that validation fails)
* Click Update
* Click Remove Issue (this does not work)

**Comment by mberhorst** [comment]
Please test it again. I updated the js which broke the deletion.

**Comment by mberhorst** [comment]
I can delete issues but it seems, that issue itself is not deleted but only the relation to the advisory.

**Comment by mberhorst** [comment]
Oh...I should read the whole comment. ;) 

Regarding my last comment, what should we do about that? Is this behaviour correct?

**Comment by helhum** [comment]
> Regarding my last comment, what should we do about that? Is this behaviour correct?

We could fix this by adding a cascade delete annotation, but I'd refrain from doing that currently.

So, the current behavior in that regard is fine for now

**Comment by helhum** [comment]
but deleting from the advisory now works, thanks
