### ISSUE TITLE
Created versions for solutions can't be deleted

### ISSUE THREAD

**Issue by mberhorst** [helhum/TYPO3.IHS#65]
This code does not seem to work and I don't know why.

```php
/** @var $product Product */
$product = $this->productRepository->findByIdentifier($productIdentifier);
$product->removeVersion($versionIdentifier);

$this->productRepository->update($product);
$this->persistenceManager->persistAll();
```

https://github.com/helhum/TYPO3.IHS/blob/master/Packages/Application/TYPO3.IHS/Classes/TYPO3/IHS/Controller/ProductController.php#L200

**Comment by skurfuerst** [comment]
A Flow bugfix has been pushed to: https://review.typo3.org/#/c/36173/

**Comment by timkandel** [comment]
Why not just use productVersion[value]? That should work perfectly fine
