### ISSUE TITLE
Fix and streamline Advisory Data

### ISSUE THREAD

**Issue by helhum** [helhum/TYPO3.IHS#78]
Ticket to coordinate the work on updating the Data. 

Just put an advisory ID in the comment if you start working on it and add a comment when you finished updating.

This is all about not doing duplicate or conflicting work.

**Comment by helhum** [comment]
TYPO3-CORE-SA-2015-001

**Comment by t3sec** [comment]
TYPO3-20050304-1 (starting extension issues from past till today)

**Comment by IchHabRecht** [comment]
Last week:
TYPO3-20050307-1
TYPO3-20050725-1
TYPO3-20050822-1

**Comment by IchHabRecht** [comment]
TYPO3-20051010-10
TYPO3-20051107-1
TYPO3-20051107-2
TYPO3-20051114-1
TYPO3-20051114-2
TYPO3-20051114-3
TYPO3-20051114-4
TYPO3-20051114-5
TYPO3-20051114-6
TYPO3-20051114-7

**Comment by IchHabRecht** [comment]
All bulletins till TYPO3-SA-2009-005 are covered

**Comment by maddy2101** [comment]
missing advisories in IHS:
TYPO3-EXT-SA-2015-022
TYPO3-EXT-SA-2015-021
TYPO3-EXT-SA-2015-020
TYPO3-EXT-SA-2015-019
TYPO3-EXT-SA-2015-018
TYPO3-EXT-SA-2015-017
TYPO3-EXT-SA-2015-016
TYPO3-CORE-SA-2015-009
TYPO3-CORE-SA-2015-008
TYPO3-CORE-SA-2015-007
TYPO3-CORE-SA-2015-006
TYPO3-CORE-SA-2015-005
TYPO3-CORE-SA-2015-004
TYPO3-CORE-SA-2015-003
TYPO3-CORE-SA-2015-002

as of command, starting from the start:
TYPO3-EXT-SA-2015-009
TYPO3-EXT-SA-2015-005
TYPO3-EXT-SA-2015-004
