### ISSUE TITLE
Only newer TYPO3 versions are available as versions for TYPO3 CMS

### ISSUE THREAD

**Issue by helhum** [helhum/TYPO3.IHS#80]
Not sure what the exact problem is, but I right now cannot set select versions older than 6.2.0

**Comment by timkandel** [comment]
That's because TYPO3 is currently imported from packagist where only the 6.2 and 7.x tags are.
Either you need to make sure all tags are available on packagist or we need another source

**Comment by timkandel** [comment]
Will be fixed with integration of get.typo3.org import
