### ISSUE TITLE
What should we do with "severity" from current advisories

### ISSUE THREAD

**Issue by helhum** [helhum/TYPO3.IHS#82]
Did we have any plans how to handle the severity? Should this be calculated from the CVSS?

@t3sec any comment appreciated

**Comment by t3sec** [comment]
For all existing advisories we need to take the "existing severity".

For new advisories we indeed could make severity a derived property from CVSS. I'd suggest to analyze all CVSS scores when content migration is done. Then we define thresholds for low, medium, high, critical.

**Comment by helhum** [comment]
Advisory and Issue must get a new text field "severity" which just holds a string

The getter for Severity should only calculate (implemented in 2.0) the severity if this property is empty

**Comment by helhum** [comment]
@timkandel please remove yourself if you're not going to work on this
