### ISSUE TITLE
Ordering solutions deletes a solution

### ISSUE THREAD

**Issue by helhum** [helhum/TYPO3.IHS#92]
To reproduce:

* Go to https://ihs.timkandel.de/security-bulletins/edit?advisory%5B__identity%5D=TYPO3-CORE-SA-2015-001
* Expand Issue
* Expand both solutions
* Click the "up" button of the last solution

Expected result: Ordering of solutions change
Actual result: Second solution is "deleted"

Tested in Safari 7.1.3 if that matters.

**Comment by mberhorst** [comment]
I tested the problem and could not reproduce it.

**Comment by t3sec** [comment]
Cannot reproduce with Chrome v41 on production (today).

**Comment by timkandel** [comment]
Problem solved during todays stand up :)

**Comment by helhum** [comment]
Was a Layer 8 problem...
