### ISSUE TITLE
Bulletin quick filter not working

### ISSUE THREAD

**Issue by t3sec** [helhum/TYPO3.IHS#96]
The bulletin quick filter introduced with #94 does not seem to work (on production). When "has issue(s): no" is selected, no bulletins are displayed. In this case a lot of bulletins should be listed. Have a look on e.g. https://ihs.timkandel.de/security-bulletin/typo3-20070719-1 - no issue is assigned; it should appear with this filter.

**Comment by mberhorst** [comment]
The thing is, none of the filters are working. oO

**Comment by mberhorst** [comment]
I think the "has issues" filter should not be usable for users that are not authenticated.

**Comment by t3sec** [comment]
> I think the "has issues" filter should not be usable for users that are not authenticated.

This is correct.
